use map for icons
jovandeginste/workout-tracker pull request #291
Opened 2024-09-09 12:29 UTC by Monirzadeh

it is related to #284 
later i will review that code to make that better but for now try to fix golangci-lint error that remain in code 

Note: why i don't use single map? i am not complety read the code right now but if should search in maps multiple time maybe smaller map be better instead of load the full map each time . beside ram usage it can affect search time in map (i will review that later and try to find a better solution for that)

2024-09-10 07:32 UTC, jovandeginste commented
> @jovandeginste do you think we need `gofumpt`? relay `gofmt` is not enough?

I'd rather have `gofumpt` enabled, yes

2024-09-10 11:52 UTC, jovandeginste commented
Can we merge all maps into one now, with a single lookup function? I split them originally because the linter complained... If the linter is happy with a single map, we should then sort the map alphabetically...

2024-09-11 09:25 UTC, jovandeginste requested changes
one final request, then it's good for me

2024-09-11 09:25 UTC, jovandeginste commented on pkg/templatehelpers/icons.go
> -	// We need every icon fully qualified here. Otherwise Tailwind will not pick
Can you keep this comment, eg. above the iconMap declaration?

2024-09-11 15:03 UTC, Monirzadeh commented on pkg/templatehelpers/icons.go
> -	// We need every icon fully qualified here. Otherwise Tailwind will not pick
done

2024-09-11 15:53 UTC, jovandeginste approved these changes

2024-09-11 15:55 UTC, merged

2024-09-11 15:55 UTC, jovandeginste commented
Thanks, merged!